# docker-compose.yml
version: "3.4"

services:
  flask-server:
    image: flask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5050:5050
      - 10001:10001
    volumes:
      - .:/app:cached