# docker-compose.yml
version: "3.4"

services:
  flask-server:
    build: .
    ports:
      - 5050:5050
      - 10001:10001
    volumes:
      - .:/app
      - /var/anchore-reports:/app/app/anchore-reports
    environment: 
      - FLASK_APP=secdash.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5050
      - FLASK_ENV=development
  
  # Temp disable
  #redis-server:
  #  image: redis:4.0.12
  #  ports:
  #    - 36511:36511
  #  volumes:
  #    - .redis/config/redis.conf:/redis.conf
  #  command: ["redis-server", "redis.confg requirepass atmv4cajDbQimGXgQ6uyEpghfLNz4hG1l6Nw38LS"]
